apiVersion: v1
kind: Service
metadata:
  name: php-service
  annotations:
    metallb.universe.tf/allow-shared-ip: default
  labels:
    app: phpmyadmin
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.112
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: phpmyadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: php_img
        imagePullPolicy: Never
        name: phpmyadmin
        ports:
        - containerPort: 5000