apiVersion: v1
kind: Service
metadata:
  name: influx-service
spec:
  selector:
    app: influxdb
  type: ClusterIP
  ports:
    - protocol: TCP
      name: api-port
      port: 8086
      targetPort: 8086
    - protocol: TCP
      name: interface-port
      port: 8088
      targetPort: 8088
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx-deployment
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        image: influx_img
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
        - containerPort: 8088
        volumeMounts:
        - name: influxdb-claim
          mountPath: /var/lib/influxdb
      volumes:
      - name: influxdb-claim
        persistentVolumeClaim:
          claimName: influxdb-pvc